language: android
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25
  licenses:
    - 'android-sdk-license-.+'
    - 'android-sdk-preview-license-.+'

jdk:
    - oraclejdk8